name: test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aquaproj/aqua-installer@v1.2.0
        with:
          aqua_version: v1.30.0
      - run: terraform-docs . > README.md
      - run: |
          if ! git diff --exit-code README.md; then
            echo "::error file=README.md,title=Please run 'terraform-docs . > README.md'::Please run 'terraform-docs . > README.md'"
            exit 1
          fi
      - run: tflint
      - run: cp config.yaml.tmpl config.yaml
      - run: cp secret.yaml.tmpl secret.yaml
      - run: cp secret_trigger_workflow.yaml.tmpl secret_trigger_workflow.yaml
      - run: bash download-zip.sh
      - run: terraform init
      - run: terraform fmt -check
      - run: terraform validate
